### ISSUE TITLE
Divide by zero error in calculate_stats.py

### ISSUE THREAD

**Issue by psymar** [paoloruiz/ootp-pt-analysis#1]
Traceback (most recent call last):
  File "C:\Users\johnm\Dropbox\ootp-pt-analysis\generate_sheet.py", line 47, in <module>
    splits = get_splits(ovr_data_ylt, vl_data_ylt, vr_data_ylt, vl_data, vr_data)
  File "C:\Users\johnm\Dropbox\ootp-pt-analysis\stats\splits\calculate_splits.py", line 8, in get_splits
    "fielder": sum(map(lambda gs_stats: gs_stats["gs"], fielder_full_time)) / len(fielder_full_time),
ZeroDivisionError: division by zero

I assume someone in one of my tournaments got used only as a DH, PH or PR and thus had no fielding data.
Easy enough to fix with "0 if len(variable)==0 else (quotient)", but has to be fixed for each fielding data line and catching line.

**Comment by psymar** [comment]
After fixing these I got a float div by zero in calculate_league_stats.py.  I'll submit a PR with fixes :)

**Comment by psymar** [comment]
Lots of empty lists being regressed?  I am starting to think it's trying to use leageu data when I don't have any (only tournaments)

**Comment by psymar** [comment]
Never mind; the fix was apparently to edit the defaults in generate_sheet to allow Stone leagues to count (my data didn't have Iron+)

**Comment by paoloruiz** [comment]
Yeah as a follow up - I'm adapting this code from a more complete but much more byzantine version of a private repo I had and made assumptions about when this data would be used. It assumes perfect leagues exist or stuff along those lines.

**Comment by trosene** [comment]
@psymar can you elaborate on your fix a bit more? I edited generate_sheet.py and set min level to "St". I get the same division by zero error though.

**Comment by psymar** [comment]
> 
> 
> @psymar can you elaborate on your fix a bit more? I edited generate_sheet.py and set min level to "St". I get the same division by zero error though.

My guess is your problem has to do with the filenames; they have to be of the format:
YYYY_StNNN_Ovr.csv
YYYY_StNNN_vL.csv
YYYY_StNNN_vR.csv

e.g. 2023_St135_Ovr.csv

and those have to be underscores (shift-hyphen), not spaces.  Also, if you're somehow in a league where the number is less than 3 digits, you'll need to pad it with zeroes.
